#!/bin/bash

species=("A. splendens vs T. elongatum" "A. splendens vs C. macrourus" "A. searsii vs O. sativa" "A. searsii vs C. macrourus" "A. searsii vs C. lacryma.jobi" "A. sativa.ot3098 vs B. tectorum" "B. distachyon vs O. sativa" "C. macrourus vs P. hallii" "C. virgata vs S. italica" "C. virgata vs T. elongatum" "C. lacryma.jobi vs T. elongatum" "E. colona vs P. hallii" "E. colona vs S. bicolor" "E. tef vs P. hallii" "H. marinum vs C. macrourus" "L. perrieri vs T. monococcum" "O. sativa vs T. monococcum" "P. annua vs S. italica" "S. spontaneum vs P. hallii" "S. spontaneum vs S. viridis" "S. spontaneum vs T. elongatum" "S. spontaneum vs C. macrourus" "S. cereale vs S. viridis" "S. italica vs P. hallii" "S. italica vs L. perrieri" "S. italica vs A. sativa.ot3098" "S. viridis vs P. hallii" "S. viridis vs S. bicolor" "S. bicolor vs L. perenne" "T. monococcum vs Z. mays")
collinearity=("Achnatherum.splendens1_Thinopyrum.elongatum2" "Achnatherum.splendens2_Cenchrus.macrourus2" "Aegilops.searsii1_Oryza.sativa1" "Aegilops.searsii2_Cenchrus.macrourus1" "Aegilops.searsii2_Coix.lacryma.jobi1" "Avena.sativa.ot30981_Bromus.tectorum3" "Brachypodium.distachyon1_Oryza.sativa1" "Cenchrus.macrourus1_Panicum.hallii2" "Chloris.virgata1_Setaria.italica1" "Chloris.virgata1_Thinopyrum.elongatum1" "Coix.lacryma.jobi1_Thinopyrum.elongatum2" "Echinochloa.colona1_Panicum.hallii3" "Echinochloa.colona1_Sorghum.bicolor3" "Eragrostis.tef1_Panicum.hallii2" "Hordeum.marinum2_Cenchrus.macrourus1" "Leersia.perrieri1_Triticum.monococcum2" "Oryza.sativa1_Triticum.monococcum1" "Poa.annua1_Setaria.italica2" "Saccharum.spontaneum1_Panicum.hallii4" "Saccharum.spontaneum1_Setaria.viridis4" "Saccharum.spontaneum1_Thinopyrum.elongatum4" "Saccharum.spontaneum2_Cenchrus.macrourus4" "Secale.cereale1_Setaria.viridis1" "Setaria.italica1_Panicum.hallii1" "Setaria.italica2_Leersia.perrieri1" "Setaria.italica3_Avena.sativa.ot30981" "Setaria.viridis1_Panicum.hallii1" "Setaria.viridis1_Sorghum.bicolor1" "Sorghum.bicolor1_Lolium.perenne1" "Triticum.monococcum2_Zea.mays1")

for folder_index in "${!species[@]}"; do {
        collinearity_file=${collinearity[$folder_index]}
        python distance.py collinearity/"${collinearity_file}".collinearity "distance.txt" "${species[$folder_index]}"
}&
done
wait
